[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirections pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = "Host"

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://connect.facebook.net https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https:; frame-src https:;"

# Cache des assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour les images
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Rate limiting pour éviter les attaques
[[edge_functions]]
  function = "rate-limit"
  path = "/api/*"

# Configuration des formulaires
[forms]
  settings = { }

# Variables d'environnement pour la production
[context.production.environment]
  VITE_GA_MEASUREMENT_ID = ""
  VITE_META_PIXEL_ID = ""

# Configuration pour les campagnes publicitaires
[context.production]
  command = "npm run build"

# Optimisation des fonctions (pas utilisées mais prêt pour scale)
[functions]
  directory = "netlify/functions"
  included_files = ["package.json"]

# Configuration avancée pour high traffic
[[edge_functions]]
  function = "geolocation"
  path = "/*"